CREATE DATABASE IF NOT EXISTS meraj_school CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE meraj_school;
CREATE TABLE admins (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE media (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 type ENUM('gallery','video') NOT NULL,
 title VARCHAR(200) NOT NULL,
 description TEXT NULL,
 file_path VARCHAR(255) NOT NULL,
 published TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX(type), INDEX(published), INDEX(created_at)
);
