<?php
session_start(); require 'config.php';
$gallery = db()->query("SELECT * FROM media WHERE type='gallery' AND published=1 ORDER BY created_at DESC LIMIT 8")->fetchAll();
$videos = db()->query("SELECT * FROM media WHERE type='video' AND published=1 ORDER BY created_at DESC LIMIT 3")->fetchAll();
$audios = db()->query("SELECT * FROM media WHERE type='audio' AND published=1 ORDER BY created_at DESC LIMIT 3")->fetchAll();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e(SCHOOL_NAME)?></title><link rel="stylesheet" href="assets/css/style.css"></head><body>
<header class="site-header"><div class="container nav"><a class="brand" href="index.php"><img src="assets/images/school-logo.png"><span>ME’RAJ INTERNATIONAL SCHOOL<br><small>MAIDUGURI</small></span></a><button class="nav-toggle">☰</button><nav><a href="#about">About</a><a href="#programmes">Programmes</a><a href="apply.php" class="nav-apply">Apply Now</a><a href="media.php?type=gallery">Gallery</a><a href="media.php?type=audio">Audio</a><a href="media.php?type=video">Video</a><a href="#contact">Contact</a></nav></div></header>
<main>
<section class="hero"><div class="hero-overlay"></div><div class="container hero-content"><span class="eyebrow">EDUCATION FOR EXCELLENCE</span><h1>Building Knowledge.<br><span>Building Character.</span></h1><p>A balanced educational experience combining Western Education, Islamic Studies and Arabic Language.</p><div class="actions"><a class="btn" href="apply.php">Apply for Admission</a><a class="btn btn-light" href="#about">Discover Our School</a></div></div></section>
<section id="about" class="section"><div class="container two-col"><div><span class="eyebrow">ABOUT OUR SCHOOL</span><h2>Welcome to Me’Raj International School Maiduguri</h2><p>Me’Raj International School is committed to providing quality, balanced and purposeful education for learners across Nursery, Primary and Secondary sections.</p><p>Our school combines academic excellence with Islamic values, Arabic Language, discipline, creativity and good character, preparing learners to become confident, responsible and useful members of society.</p></div><img class="rounded" src="assets/images/students.jpg" alt="Me’Raj International School students"></div></section>
<section id="programmes" class="section alt"><div class="container"><span class="eyebrow">OUR PROGRAMMES</span><h2>Three Pillars of Learning</h2><div class="cards"><article><div class="icon">01</div><h3>Western Education</h3><p>English Language, Mathematics, Basic Science, Computer Studies, Agricultural Science, C.C.A., History, Religion and National Values, Home Economics and Handwriting.</p></article><article><div class="icon">02</div><h3>Islamic Studies</h3><p>Qur’an, Hadith, Fiqh, Tawheed and Islamic Religious Studies, with emphasis on understanding and practising Islamic teachings.</p></article><article><div class="icon">03</div><h3>Arabic Language</h3><p>Arabic Language and Mutalaa, developing reading, writing, comprehension and communication skills.</p></article></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">SCHOOL GALLERY</span><h2>Life at Me’Raj</h2></div><a href="media.php?type=gallery" class="more">More →</a></div><div class="gallery"><?php foreach($gallery as $m): ?><a href="<?=e($m['file_path'])?>" target="_blank"><img src="<?=e($m['file_path'])?>" alt="<?=e($m['title'])?>"><span><?=e($m['title'])?></span></a><?php endforeach; if(!$gallery): ?><p class="empty">Gallery items will appear here when the Admin uploads them.</p><?php endif; ?></div></div></section>
<section class="section alt"><div class="container two-col media-promo"><div><span class="eyebrow">AUDIO LIBRARY</span><h2>Listen, Learn & Benefit</h2><p>Browse Qur’an recitations, Islamic lectures and school recordings.</p><a href="media.php?type=audio" class="more">More →</a></div><div class="media-list"><?php foreach($audios as $m): ?><div class="media-item"><strong><?=e($m['title'])?></strong><audio controls src="<?=e($m['file_path'])?>"></audio></div><?php endforeach; ?></div></div></section>
<section class="section"><div class="container two-col media-promo"><div><span class="eyebrow">VIDEO LIBRARY</span><h2>Watch. Learn. Experience.</h2><p>Watch Qur’an recitations, Islamic lectures, school activities and special events.</p><a href="media.php?type=video" class="more">More →</a></div><div class="video-grid"><?php foreach($videos as $m): ?><video controls preload="metadata" src="<?=e($m['file_path'])?>"></video><?php endforeach; ?></div></div></section>
<section id="contact" class="section contact"><div class="container"><span class="eyebrow">CONTACT US</span><h2>We Would Love to Hear From You</h2><p>No. 18 Circular Road, GRA, Maiduguri, Borno State, Nigeria</p><p><strong>08026798386 / 08038978383</strong></p><a class="btn" href="apply.php">Start Your Admission Application</a></div></section>
</main><footer><div class="container"><strong>ME’RAJ INTERNATIONAL SCHOOL MAIDUGURI</strong><span>Educational Excellence</span></div></footer><script src="assets/js/app.js"></script></body></html>