<?php require 'config.php';
$gallery=db()->query("SELECT * FROM media WHERE type='gallery' AND published=1 ORDER BY created_at DESC LIMIT 8")->fetchAll();
$videos=db()->query("SELECT * FROM media WHERE type='video' AND published=1 ORDER BY created_at DESC LIMIT 4")->fetchAll();
$slides=[['assets/images/students.jpg','Our Students'], ...array_map(fn($m)=>[$m['file_path'],$m['title']],array_slice($gallery,0,3))];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e(SCHOOL_NAME)?></title><meta name="description" content="<?=e(SCHOOL_NAME)?> — <?=e(SCHOOL_MOTTO)?>"><link rel="stylesheet" href="assets/css/style.css"></head>
<body>
<header class="site-header"><div class="container nav"><a class="brand" href="#home"><img src="assets/images/school-logo.png" alt="School logo"><span>ME’RAJ INTERNATIONAL SCHOOL<br><small>MAIDUGURI</small></span></a><button class="nav-toggle" aria-label="Menu">☰</button><nav class="site-nav"><a href="#home">Home</a><a href="#about">About Us</a><a href="#programs">Programs</a><a href="#gallery">Gallery</a><a href="#videos">Videos</a><a href="#contact">Contact</a></nav></div></header>
<main>
<section id="home" class="hero"><div class="hero-slides"><?php foreach($slides as $i=>$s): ?><div class="hero-slide<?= $i===0?' active':'' ?>" style="background-image:url('<?=e($s[0])?>')"></div><?php endforeach; ?></div><div class="hero-overlay"></div><div class="container hero-content"><span class="eyebrow light">EDUCATIONAL EXCELLENCE</span><h1>Building Knowledge.<br><span>Building Character.</span></h1><p>Quality education for confident, disciplined and responsible learners.</p><div class="actions"><a class="btn" href="#programs">Explore Our Programs</a><a class="btn btn-outline" href="#contact">Contact Us</a></div></div><button class="slider-arrow prev" aria-label="Previous">‹</button><button class="slider-arrow next" aria-label="Next">›</button><div class="dots"><?php foreach($slides as $i=>$s): ?><button class="dot<?= $i===0?' active':'' ?>" data-slide="<?=$i?>"></button><?php endforeach; ?></div></section>
<section class="school-banner"><div class="container plaque"><div class="ornament">✦</div><h2>ME’RAJ INTERNATIONAL SCHOOL</h2><p>MAIDUGURI</p><span><?=e(SCHOOL_MOTTO)?></span></div></section>
<section id="about" class="section"><div class="container two-col"><div><span class="eyebrow">ABOUT OUR SCHOOL</span><h2>Welcome to <?=e(SCHOOL_NAME)?></h2><p>We provide a balanced educational environment that develops academic ability, good character, confidence and practical skills.</p><p>Our learners are guided to grow in knowledge, discipline, creativity and responsible citizenship.</p><div class="feature-grid"><div><b>01</b><strong>Academic Excellence</strong></div><div><b>02</b><strong>Good Character</strong></div><div><b>03</b><strong>Modern Learning</strong></div><div><b>04</b><strong>Responsible Citizenship</strong></div></div></div><div class="image-frame"><img src="assets/images/students.jpg" alt="Students of Me’Raj International School"></div></div></section>
<section id="programs" class="section alt"><div class="container"><span class="eyebrow">OUR PROGRAMS</span><h2>A Complete Learning Experience</h2><div class="cards"><article><div class="icon">01</div><h3>Early Years & Primary</h3><p>Strong foundations in literacy, numeracy, creativity, values and confident learning.</p></article><article><div class="icon">02</div><h3>Secondary Education</h3><p>Focused academic preparation, digital skills, critical thinking and personal development.</p></article><article><div class="icon">03</div><h3>Islamic & Moral Education</h3><p>Learning that encourages discipline, respect, responsibility and positive character.</p></article></div></div></section>
<section id="gallery" class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">SCHOOL GALLERY</span><h2>Moments at Me’Raj</h2></div><a class="more" href="gallery.php">View All →</a></div><div class="gallery-grid"><?php foreach($gallery as $m): ?><a class="gallery-card" href="<?=e($m['file_path'])?>" target="_blank"><img src="<?=e($m['file_path'])?>" alt="<?=e($m['title'])?>"><span><?=e($m['title'])?></span></a><?php endforeach; ?><?php if(!$gallery): ?><div class="empty">Gallery photos uploaded by the Admin will appear here.</div><?php endif; ?></div></div></section>
<section id="videos" class="section alt"><div class="container"><div class="section-head"><div><span class="eyebrow">VIDEO LIBRARY</span><h2>School Activities & Events</h2></div><a class="more" href="videos.php">View All →</a></div><div class="video-grid"><?php foreach($videos as $m): ?><article class="video-card"><video controls preload="metadata" src="<?=e($m['file_path'])?>"></video><h3><?=e($m['title'])?></h3><p><?=e($m['description'])?></p></article><?php endforeach; ?><?php if(!$videos): ?><div class="empty">Videos uploaded by the Admin will appear here.</div><?php endif; ?></div></div></section>
<section id="contact" class="contact-section"><div class="container contact-grid"><div><span class="eyebrow light">FIND US</span><h2>Visit Me’Raj International School Maiduguri</h2><p><?=e(SCHOOL_ADDRESS)?></p><p class="phones"><a href="tel:<?=e(SCHOOL_PHONE_1)?>"><?=e(SCHOOL_PHONE_1)?></a><br><a href="tel:<?=e(SCHOOL_PHONE_2)?>"><?=e(SCHOOL_PHONE_2)?></a></p><div class="actions"><a class="btn" href="https://wa.me/<?=e(SCHOOL_WHATSAPP)?>" target="_blank">WhatsApp</a><a class="btn btn-outline" href="https://www.google.com/maps/search/?api=1&query=<?=rawurlencode(SCHOOL_ADDRESS)?>" target="_blank">Open Location</a></div></div><div class="map-box"><iframe title="School location" loading="lazy" src="https://www.google.com/maps?q=<?=rawurlencode(SCHOOL_ADDRESS)?>&output=embed"></iframe></div></div></section>
</main><footer><div class="container footer-inner"><div><img src="assets/images/school-logo.png" alt="Logo"><strong>ME’RAJ INTERNATIONAL SCHOOL MAIDUGURI</strong></div><p>© <span data-year></span> <?=e(SCHOOL_NAME)?>. All rights reserved.</p></div></footer><script src="assets/js/app.js"></script></body></html>
